data:
  mushroom:
    path: "data/02_mushroom_species_data.csv"


model:
  mushroom:
    path: "models/mushroom-pipeline"


columns:
  mushroom: 
    - "cap-shape"
    - "cap-surface"
    - "cap-color"
    - "bruises"
    - "odor"
    - "gill-attached"
    - "gill-spacing"
    - "gill-size"
    - "gill-color"
    - "stalk-shape"
    - "stalk-root"
    - "stalk-surface-above-ring"
    - "stalk-surface-below-ring"
    - "stalk-color-above-ring"
    - "stalk-color-below-ring"
    - "veil-color"
    - "ring-number"
    - "ring-type"
    - "spore-print-color"
    - "population"
    - "habitat"


