data: # get the data
  mushroom:
    path: "data/02_mushroom_species_data.csv"

  housing: 
    path: "data/housing_clean.xlsx"


model: # path to pipeline
  mushroom:
    path: "models/mushroom-pipeline"
  housing:
    path: "models/house-pipeline"

columns: # for list
  mushroom: 
    - "bruises"
    - "odor"
    - "gill-size"
    - "gill-color"
    - "stalk-surface-above-ring"
    - "ring-type"
    - "spore-print-color"

  housing:
    - "town"
    - "street_name"
    - "postal_code"
    - "month"
    - "flat_type"
    - "flat_model"
    - "floor_area_sqm"
    - "storey_range"
    - "lease_commence_date"
    - "cbd_dist"
    - "min_dist_mrt"





